/*
 Generated by typeshare 1.13.2
*/

export interface AuthResponse {
	url: string;
}

export interface AuthenticateQueryParams {
	client_id: string;
}

export interface AuthenticateRequest {
	username?: string;
	password?: string;
}

export interface AuthenticateResponse {
	url: string;
}

export interface JwtToken {
	access_token: string;
	token_type: string;
	refresh_token: string;
	expires_in: number;
	id_token: string;
}

export enum GrantType {
	Code = "authorization_code",
	Password = "password",
	Credentials = "client_credentials",
	RefreshToken = "refresh_token",
}

export interface TokenRequestValidator {
	grant_type?: GrantType;
	client_id?: string;
	client_secret?: string;
	code?: string;
	username?: string;
	password?: string;
	refresh_token?: string;
}

