/*
 Generated by typeshare 1.13.2
*/

export interface RedirectUri {
	id: string;
	client_id: string;
	value: string;
	enabled: boolean;
	created_at: Date;
	updated_at: Date;
}

export interface Client {
	id: string;
	enabled: boolean;
	client_id: string;
	secret?: string;
	realm_id: string;
	protocol: string;
	public_client: boolean;
	service_account_enabled: boolean;
	client_type: string;
	name: string;
	redirect_uris?: RedirectUri[];
	created_at: Date;
	updated_at: Date;
}

export interface CredentialData {
	hash_iterations: number;
	algorithm: string;
}

export interface CredentialOverview {
	id: string;
	user_id: string;
	credential_type: string;
	user_label?: string;
	credential_data: CredentialData;
	created_at: Date;
	updated_at: Date;
}

export interface JwkKey {
	kid: string;
	kty: string;
	use_: string;
	alg: string;
	x5c: string;
	n: string;
	e: string;
}

export interface JwtToken {
	access_token: string;
	token_type: string;
	refresh_token: string;
	expires_in: number;
	id_token: string;
}

export interface Realm {
	id: string;
	name: string;
	created_at: Date;
	updated_at: Date;
}

export interface Role {
	id: string;
	name: string;
	description?: string;
	permissions: string[];
	realm_id: string;
	client_id: string;
	client?: Client;
	created_at: Date;
	updated_at: Date;
}

export enum RequiredAction {
	ConfigureOtp = "configure_otp",
	VerifyEmail = "verify_email",
	UpdatePassword = "update_password",
}

export interface User {
	id: string;
	realm_id: string;
	client_id: string;
	username: string;
	firstname: string;
	lastname: string;
	email: string;
	email_verified: boolean;
	enabled: boolean;
	roles: Role[];
	realm?: Realm;
	required_actions: RequiredAction[];
	created_at: Date;
	updated_at: Date;
}

export enum AuthenticationStepStatus {
	Success = "Success",
	RequiresActions = "RequiresActions",
	RequiresOtpChallenge = "RequiresOtpChallenge",
	Failed = "Failed",
}

export enum ClaimsTyp {
	Refresh = "Refresh",
	Bearer = "Bearer",
}

export enum GrantType {
	Code = "authorization_code",
	Password = "password",
	Credentials = "client_credentials",
	RefreshToken = "refresh_token",
}

export enum Permissions {
	CreateClient = "create_client",
	ManageAuthorization = "manage_authorization",
	ManageClients = "manage_clients",
	ManageEvents = "manage_events",
	ManageIdentityProviders = "manage_identity_providers",
	ManageRealm = "manage_realm",
	ManageUsers = "manage_users",
	ManageRoles = "manage_roles",
	QueryClients = "query_clients",
	QueryGroups = "query_groups",
	QueryRealms = "query_realms",
	QueryUsers = "query_users",
	ViewAuthorization = "view_authorization",
	ViewClients = "view_clients",
	ViewEvents = "view_events",
	ViewIdentityProviders = "view_identity_providers",
	ViewRealm = "view_realm",
	ViewUsers = "view_users",
	ViewRoles = "view_roles",
}

